### ISSUE TITLE
Тренировка 10

### ISSUE THREAD

**Issue by zarsky** [Mykhailo-Granik/ACM-Solutions#1]
Что-то нигде не могу отыскать разбор 10-й тренировки, он был, или еще нет?

**Comment by Mykhailo-Granik** [comment]
Его не было, и он врядли будет (им интересовался только ты). Если есть
вопросы по задачам - пиши

**Comment by zarsky** [comment]
В общем-то все удалось порешать, кроме [задачи G](http://codeforces.com/group/YnciCj8uVi/contest/205231/problem/G) - напиши плиз в 2-х словах, в чем там суть.

**Comment by Mykhailo-Granik** [comment]
Разбор от авторов задачи:

Так, как _gcd_(1, _m_) = 1, то при _n_ = _k_ ответа не существует.

Воспользуемся фактом, что _gcd_(_m_, _m_ - 1) = 1 и построим такую
перестановку:

_n_ - _k_  1  2  3  ...   _n_ - _k_ - 1  _n_ - _k_ + 1  _n_ - _k_ + 2  ...
  _n_

2016-01-27 21:05 GMT+02:00 zarsky notifications@github.com:

**Comment by zarsky** [comment]
Ок, спасибо
Кстати, следующая лекция уже в следующий четверг будет? 4-го?

**Comment by Mykhailo-Granik** [comment]
Вероятно да

27 января 2016 г., 21:27 пользователь zarsky notifications@github.com
написал:
